#ifndef XTRA_LOG_HH
#define XTRA_LOG_HH

#include "soil/Log.hh"

#define XTRA_LOG_INIT(x) SOIL_LOG_INIT(x)

#define XTRA_TRACE SOIL_TRACE
#define XTRA_DEBUG SOIL_DEBUG
#define XTRA_INFO  SOIL_INFO
#define XTRA_WARNING SOIL_WARNING
#define XTRA_ERROR SOIL_ERROR
#define XTRA_FATAL SOIL_FATAL
#define XTRA_PDU SOIL_PDU


#endif
